feature_net_kwargs:
  rgb_feat:
    cls: ImgFeat
    output_dim: 512
  compass:
    cls: CompassMLP
    input_dim: 4
    hidden_dim: 128
    output_dim: 128
    hidden_depth: 2
  gps:
    cls: GPSMLP
    hidden_dim: 128
    output_dim: 128
    hidden_depth: 2

feature_fusion:
  output_dim: 512
  hidden_depth: 0

actor:
  hidden_dim: 256
  hidden_depth: 3

critic:
  hidden_dim: 256
  hidden_depth: 3

agent:
  task: "combat spider"
  prompt: "spider . sword . sky . mob . tree ."
  num_envs: 1
  total_timesteps: 500000
  num_steps: 5000
  num_minibatches: 5
  learning_epochs: 10

  load_ppo_model: false
  ppo_checkpoint_path: ""
  load_image_model: false
  image_checkpoint_path: ""

  train_image_model: false
  lora_rank: 64
  lora_alpha: 64

  policy_learning_rate: !!float 1e-4 #1e-4
  vision_learning_rate: !!float 1e-4 #1e-4
  min_lr: !!float 1e-6
  gamma: 0.99
  gae_lambda: 0.95
  clip_coef: 0.2
  ent_coef: 0.005
  vf_coef: 0.5
  max_grad_norm: 10
  seed: 1

  cuda_number: 0
  wandb_init: false
